config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength

Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql" if Rails.env.development?

  post "/graphql", to: "graphql#execute"
  devise_for :users, controllers: { sessions: "account/sessions",
                                    registrations: "account/registrations",
                                    confirmations: "account/confirmations",
                                    invitations: "account/invitations",
                                    passwords: "account/passwords" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  namespace :api do
    resources :output_assets
    resources :input_job_assets
    resources :assets
    resources :job_status
    mount_devise_token_auth_for "User", at: :auth, skip: [:omniauth_callbacks], controllers: {
      sessions: "api/sessions"
    }
  end

  namespace :account do
    get "/dashboard", to: "dashboard#index"
    resources :output_assets
    resources :profiles
    get "/output_assets/:id/download", to: "output_assets#download", as: :output_asset_download
    resources :classifiers do
      resources :input_assets
      resources :labels
      resources :jobs
    end
  end
end
# rubocop:enable Metrics/BlockLength

app/views/shared/_alerts.html.erb
<% unless notice.blank? %>
  <p class="alert alert-primary" style="margin: 0"><%= notice %></p>
<% end %>
<% unless alert.blank? %>
  <p class="alert alert-danger" style="margin: 0"><%= alert %></p>
<% end %>

app/views/shared/_build_cards.html.erb
<% if builds.empty? %>
  <div class="alert alert-secondary" style="margin: 2rem 0">
    No builds yet
  </div>
<% end %>
<div class="build-cards" id="build-list">
	<div class="builds">
		<% builds.each do |job| %>
      <a id="jid-<%= job.id %>" href="<%= account_classifier_job_path(job.classifier, job)  %>" class="card <%= job.id == highlighted&.id ? "job-card-highlighted" : "" %> job-card" style="">
				<div class="card-header text-center">
					<small class="status status-<%= job.status %>"><%= job.status %></small>
				</div>
				<div class="card-footer">
					<div class="row">
						<div class="col-6">
							<div class="">#<%= job.job_number %></div>
						</div>
						<div class="col-6 text-right">
							<small class="align-self-end"  ><i class="fa fa-clock" style="font-weight: normal"></i> <%= job.clock_time %></small>
						</div>
					</div>
				</div>
			</a>
		<% end %>
	</div>
</div>

<script>
$(function() {
  var emt = document.getElementById('jid-<%= highlighted&.id %>');
  if (emt) {
    document.getElementById('build-list').scrollTop = emt.offsetTop - 10;
  }
});
</script>

app/views/shared/_classifier_header.html.erb
<div class="row justify-content-between" style="border-bottom: 1px solid #999">
  <div class="col-md-6">
    <div><%= classifier.name %><br/>
    <small class="text-muted"><%= classifier.model_type %>, <%= number_to_human_size(classifier.calculate_bytes) %></small>
    </div>
  </div>
  <div class="align-end" style="padding-right: 1rem;">
    <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
      <div class="btn-group btn-group-sm" role="group" aria-label="First group">
        <%= link_to '<i class="fa fa-tags"></i> Edit Labels'.html_safe,
          edit_account_classifier_path(classifier), {
          class: "btn #{active == :labels ? "btn-dark " : "btn-outline-dark"}"
        } %>
        <%= link_to '<i class="fa fa-images"></i> Edit Training Images'.html_safe,
          account_classifier_input_assets_path(classifier), {
          class: "btn #{active == :images ? "btn-dark " : "btn-outline-dark"}"
        } %>
        <%= link_to '<i class="fa fa-play"></i> Build'.html_safe,
          account_classifier_jobs_path(classifier), {
          method: :post,
          class: "btn btn-outline-primary"
        } %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer_public.html.erb
<footer class="pg-footer text-muted">
  <div class="container">
    <ul class="pg-footer-links">
      <li><a href="/guides/">Guides</a></li>
      <li><a href="/terms">Terms</a></li>
    </ul>
    <p>&copy; patterngap</p>
  </div>
</footer>

app/views/shared/_head_section_public.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<link href="https://fonts.googleapis.com/css?family=Medula+One|Open+Sans|Raleway" rel="stylesheet">
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag 'marketing', media: 'all' %>

app/views/shared/_job_navbar_account.html.erb
<nav class="col-2 bd-sidebar build-bar">
  <p class="build-bar-title">Recent Builds</p>
  <div class="list-group">
    <% classification_jobs.each do |job| %>
        <%= link_to account_classifier_job_path(classifier_id: job.classifier_id,
                                                id: job.id ), class: "list-group-item justify-content-between" do  %>
          <div style="height: 100%; width: 10px; left: 0; top: 0; position: absolute;" class="status-<%= job.status %>"></div>
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1"><%=job.job_id %></h5>
            <small><%= time_ago_in_words(job.created_at) %> ago</small>
          </div>
        <% end %>
    <% end %>
  </div>
</nav>

app/views/shared/_top_navbar_account.html.erb
<header class="navbar navbar-expand navbar-dark flex-column flex-md-row bd-navbar masthead">
  <a class="navbar-brand" href="/account/dashboard">patterngap
    <sup>
      <span class="badge badge-warning" style="font-size: 0.6rem; font-family: monaco">𝜶lpha</span>
    </sup>
  </a>
	<div class="navbar-nav-scroll">
    <ul class="navbar-nav bd-navbar-nav flex-row nav-masthead">
			<li class="nav-item <%= params[:controller] == 'account/dashboard' ? 'active' : '' %>">
				<%= link_to "Dashboard", account_dashboard_path, { class: "nav-link" } %>
			</li>
			<li class="nav-item <%= params[:controller] == 'account/classifiers' ? 'active' : '' %>">
				<%= link_to "How to Use", account_classifiers_path, { class: "nav-link" } %>
			</li>
		</ul>
	</div>
	<ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex nav-masthead">
		<li class="nav-item  <%= params[:controller] == 'account/profiles' ? 'active' : '' %>">
			<%= link_to "<i class='fas fa-user'></i> #{current_user.email}".html_safe , account_profiles_path, { class: "nav-link" } %>
		</li>
		<li class="nav-item">
			<%= link_to "Sign Out", destroy_user_session_path, { method: :delete, class: "nav-link" } %>
		</li>
	</ul>
</header>